### ISSUE TITLE
Login with tokens

### ISSUE THREAD

**Issue by Coral-afk** [ading2210/edulastic-tools#8]
![image](https://github.com/ading2210/edulastic-tools/assets/90165691/7aa88bfa-a32e-4ea9-851a-0cf2506550ef)

Could someone provide guidance on which tokens should be entered on the prompt?
because i tried putting "tokens" from the local storage and "tokenKey" , "deafultTokenKey" on the session storage and it didn't work

**Comment by ading2210** [comment]
I believe the the tokens stored in localstorage are encoded in JSON, so you would have to extract the individual token and then input it into the script.
